package com.radmir.manager.model;

public enum UserState {
    DEFAULT,

    // --- Витрати ---
    AWAITING_NAME, AWAITING_DATE, AWAITING_PRICE, AWAITING_DAYS,
    AWAITING_DELETE_ID, AWAITING_EXTENSION_DAYS, AWAITING_EDIT_ID, AWAITING_EDIT_VALUE,

    // --- Огороди ---
    AWAITING_OGOROD_NAME, AWAITING_OGOROD_DATE, AWAITING_OGOROD_PRICE,
    AWAITING_OGOROD_DAYS, AWAITING_OGOROD_DELETE_ID, AWAITING_OGOROD_EDIT_ID,
    AWAITING_OGOROD_EDIT_VALUE, AWAITING_OGOROD_EXTEND_DAYS,

    // --- Клієнти ---
    AWAITING_CLIENT_NICKNAME, AWAITING_CLIENT_OGOROD, AWAITING_CLIENT_UNIT,
    AWAITING_CLIENT_DURATION, AWAITING_CLIENT_PRICE, AWAITING_CLIENT_CONTACT,
    AWAITING_CLIENT_START_MODE, AWAITING_CLIENT_START_DATE,
    AWAITING_CLIENT_DELETE_ID, AWAITING_CLIENT_EDIT_ID, AWAITING_CLIENT_EDIT_VALUE,
    AWAITING_CLIENT_SEARCH,

    // НОВЕ: Дострокове завершення
    AWAITING_CLIENT_TERMINATE_ID,

    // --- Інше ---
    AWAITING_CALC_MODE, AWAITING_CALC_AMOUNT, AWAITING_CALC_PRICE,
    AWAITING_STATS_PERIOD, AWAITING_STATS_OGOROD,

    // --- Урожай ---
    AWAITING_HARVEST_GROWTH_TIME, AWAITING_HARVEST_WATER_TIME, AWAITING_HARVEST_PRICE,

    // --- Confirmation ---
    AWAITING_RESET_HARVEST_CONFIRM, AWAITING_RESET_CLIENTS_CONFIRM
}